spring:
  config:
    import: optional:file:.env[.properties]
  liquibase:
    change-log: db/changelog/db-changelog-master.xml
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chat
  jpa:
    open-in-view: false
  security:
    user:
      name: ${SPRING_USERNAME}
      password: ${SPRING_PASSWORD}