spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chat
  jpa:
    open-in-view: false

jwt:
  secret: ${JWT_SECRET}