spring:
  config:
    import: optional:file:.env[.properties]
  liquibase:
    change-log: db/changelog/db-changelog-master.xml
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chat
  jpa:
    open-in-view: false
  security:
    user:
      name: admin
      password: admin